<?php 
$banners = $block->getCollection();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$mediaUrl = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);

$bannerStatus = $objectManager->create('\Magento\Framework\App\Config\ScopeConfigInterface')->getValue('custom_config/slider_config/enabled');

$userAgent = $this->getRequest()->getHeader('User-Agent');
$server = $this->getRequest()->getServer();
$isMobileDevice = \Zend_Http_UserAgent_Mobile::match($userAgent, $server);
// if($isMobileDevice) {
//   $mediaUrl = $mediaUrl.'smallbanner/';
// }
?>


<div class="top-banner-section banner-container">
	<div id="topbanner" class="owl-carousel owl-theme">
		<?php foreach ($banners as $banner) { ?>
			<div class="banner-item">
				<div class="banner-img">
					<img class="desktop-banner" src="<?php echo $mediaUrl.$banner->getImage(); ?>" alt="<?php echo $banner->getTitle(); ?>">
					<!-- <img class="mobile-banner" src="<?php //echo $mediaUrl.'smallbanner/'.$banner->getImage(); ?>" alt="<?php echo $banner->getTitle(); ?>"> -->
				</div>
				<div class="banner-content">
					<div class="discount-amount"><?php echo $banner->getDiscountCode(); ?></div>
					<div class="main-title"><?php echo $banner->getTitle(); ?></div>
					<div class="sub-title"><?php echo $banner->getSubTitle(); ?></div>
					<a href="<?php echo $banner->getTargetUrl() ?>" class="banner-btn"><?php echo $banner->getButtonText() ?></a>
				</div>
			</div>
		<?php } ?>
	</div>
</div>
